# Довідник підрозділів (ключ -> відображувана назва)
units:
  A0989: "56 омпбр"
  "1 МПБ": "1 мотопіхотний батальйон 56 омпбр"
  "2 МПБ": "2 мотопіхотний батальйон 56 омпбр"
  "3 МПБ": "3 мотопіхотний батальйон 56 омпбр"
  "РВБ": "ремонтно-відновлювальний батальйон 56 омпбр"
  "ББС": "батальйон безпілотних систем 56 омпбр"
  "САДН": "самохідний артилерійський дивізіон 56 омпбр"
  "13 зр": "13 зенітна ракетна батарея 56 омпбр"
  "Розв. Рота": "розвідувальна рота 56 омпбр"
